# Generated by Django 5.1.7 on 2025-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_app', '0002_alter_historicalevent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='search_query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
